name: Dragon Hearts Campaign
url: "https://www.karma.net/DragonHearts"
markdown: CommonMarkGhPages
highlighter: rouge
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]